### ISSUE TITLE
error in panaceacli query account <account_panacea>

### ISSUE THREAD

**Issue by ncornejo** [medibloc/panacea-core#1]
Hello guys, 

I have a full node running but when I execute the command :
`panaceacli query account <account_panacea>`

I have this message:
Must specify these options: --chain-id  when --trust-node is false

so when change by:
`panaceacli query account <account_panacea> --chain-id panacea-1` 

I have this error:
ERROR: decoding bech32 failed: string not all lowercase or all uppercase

readding the documentation of Cosmos project I did config the panaceacli with:
`panaceacli config trust-node true`
and
`panaceacli config chain-id "panacea-1"`

when I tried with
`panaceacli config chain-id panacea-1`
the full node stop to work

so, now when execute
`panaceacli query account <account_panacea>`
I have the error:
ERROR: decoding bech32 failed: string not all lowercase or all uppercase

Thanks and congrats!
I am a great believer of this project!
Regards from Chile 🇨🇱

**Comment by ggomma** [comment]
Hello.

I think you put `<account_panacea>` without putting real address.
Would you try to use real address instead of `<account_panacea>`? 
For example `panacea14q8n0sttfv7j8gmdawnsdeyjthcjfg9jgm9cq2`

**Comment by ncornejo** [comment]
Thanks! Is working....  so is Account Address instead Account Name

Regards
