### ISSUE TITLE
Plan for upgrade comsos and tendermint core

### ISSUE THREAD

**Issue by MinseokOh** [medibloc/panacea-core#107]
hi
when looking at  `panacea-core/go.mod` file

```go
github.com/cosmos/cosmos-sdk v0.37.14
github.com/tendermint/tendermint v0.32.13
```

You can see that the old version of cosmos sdk and temdermint are used.
Cosmos and tendermint has made many improvements in security and performance.

Do you have any plans for upgrade sdk and consensus version?

**Comment by youngjoon-lee** [comment]
Thanks for opening this issue. The Panacea Team is currently working on upgrading Cosmos SDK to the latest Stargate version. We will accumulate our efforts on the issue #108, so that you can track the progress. So, I'm closing this issue.
