### ISSUE TITLE
Publish docker images to Docker Hub instead of Github Packages

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#163]
We've published docker images to Github Packages (beta), but it requires Github authentications whenever we fetch those docker images. That is so inconvenient for someone who doesn't want to keep Github tokens for just fetching docker images.

Fortunately, it seems that Docker Hub pricing policy is quite generous for open-sourced projects.
https://www.docker.com/pricing

**Comment by youngjoon-lee** [comment]
@gyuguen 
It seems that we don't need Github authentications when fetching docker images from ghcr.io:
```
docker pull ghcr.io/medibloc/panacea-core:master

master: Pulling from medibloc/panacea-core
b4d181a07f80: Already exists 
1d08865c0d7d: Pull complete 
5c33de09dd90: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:831e6fcbdc3e4b878ee5b6b1f29e88b5f73b888cf49a96bc457c09f24c71db74
Status: Downloaded newer image for ghcr.io/medibloc/panacea-core:master
ghcr.io/medibloc/panacea-core:master
```

Also, it seems that the `panacea-java` CI doesn't set any Github auth (env var, or so): https://github.com/medibloc/panacea-java/settings/secrets/actions

**Comment by gyuguen** [comment]
@youngjoon-lee 
Ah.
They couldn't download it when I tested it.
Let me test it again.

**Comment by youngjoon-lee** [comment]
Ah, I just found this post: https://blog.outsider.ne.kr/1530
This guy is saying that it's not reliable to use Docker Hub nowadays. IIRC, Docker Hub was almost bankrupted recently.
For that reason, many private projects are using AWS or GCP container registry. But for us, ghcr might be good enough.
