### ISSUE TITLE
REST `/panacea/did/v2/dids/{did}` returns `Not Implemented`

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#173]
```bash
curl -X GET localhost:1317/panacea/did/v2/dids/did:panacea:4Fsrryj58HP3zxRE9FPBcsG4EehAmoSuGXuvvpxbrziF

{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]
}
```

In the contrast, the `x/aol` REST works well.
```bash
curl localhost:1317/panacea/aol/v2/owners/panacea1cd4xv9am7xqvwxkcry9z4zdnj9vxkfwk6d5rdz/topics/87590daa-f9f6-4fe4-8189-f4c21b0744f0/records/0

{
  "record": {
    "key": "a2V5LTE=",
    "value": "dmFsdWUtMQ==",
    "nano_timestamp": "1625630533160794341",
    "writer_address": "panacea1cd4xv9am7xqvwxkcry9z4zdnj9vxkfwk6d5rdz"
  }
}
```

**Comment by youngjoon-lee** [comment]
I just found that colons in the URL path cause a problem: https://github.com/grpc-ecosystem/grpc-gateway/blob/094a6fe78b3ca888297d090185cdf30f0e42e157/runtime/mux.go#L209.
![image](https://user-images.githubusercontent.com/5462944/124873873-01d19180-e002-11eb-9e87-beec5ca1a5fc.png)

**Comment by gyuguen** [comment]
That's right. Colons can only come after the schema and host.

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

**Comment by youngjoon-lee** [comment]
Aha. Then, how about defining a request body as below:
```json
{
  "did": "did:panacea:..."
}
```
In the future, we should also accept a [resolutionMetadata](https://www.w3.org/TR/did-core/#did-resolution) anyway.

**Comment by gyuguen** [comment]
Well, then Http method needs to be changed to Post.
As far as I know requestBody is not available in GET method.

**Comment by gyuguen** [comment]
How about using it as a query parameter?

**Comment by youngjoon-lee** [comment]
Aha. right. Let's try a query parameter. I'll test it now.
