### ISSUE TITLE
Simulate a malicious node that tries to violate the `x/burn` Endblocker

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#179]
Although Cosmos says that the EndBlocker can contain state changes, I'm not sure if our `x/burn` EndBlocker is protected by malicious nodes.

While studying about Tendermint, we've found that the block header contains the merkle root of the validator set and the consensus parameters, which are updated by EndBlockers.

So, I'm curious if we also have to put something to the block header, if possible.

I think we can simply simulate a malicious node.
- Run 3 nodes with original source code
- Run a node by modifying the `x/burn` EndBlocker to send funds from the burn address to a certain address (instead of burnning).

Then, we can see the malicious node is detected by other nodes.
I guess that node will be detected, because its `AppHash` would be different from other nodes.
When the node is selected as a block proposer, it will include its `AppHash` to the block header. Then, other nodes will recognize that the `AppHash` broadcasted isn't equal to their own `AppHash`.

We can also ask the Cosmos team if our approach is safe (via Discord).

**Comment by gyuguen** [comment]
I've run three valid nodes and one malicious node.
Malicious nodes carried out the movement of burn addresses to other addresses.
As a result, as expected, an error occurred that the appHash did not match on the malicious node.
```
ERR prevote step: ProposalBlock is invalid err="wrong Block.Header.AppHash.  Expected 242491C785B8B27335837701D83FB5E0BF3134B4490D4340F071A524AD60B4DC, got 428CB87A1A4229177A69EDEA9CB809AC4748E3200C05715FF89D0D52116F2CC7" height=808 module=consensus round=1
3:39PM ERR CONSENSUS FAILURE!!! err="precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected 242491C785B8B27335837701D83FB5E0BF3134B4490D4340F071A524AD60B4DC, got 428CB87A1A4229177A69EDEA9CB809AC4748E3200C05715FF89D0D52116F2CC7" module=consensus stack="goroutine 207 [running]:\nruntime/debug.Stack(0xc0045ef370, 0x5670420, 
```

**Comment by youngjoon-lee** [comment]
Great! Then, I think we can go with our current implementation.

**Comment by gyuguen** [comment]
If a normal node is a proposer, the connection is interrupted because the malicious node has not received more than 2/3+ consensus. This does not leave an error log on the normal log.

If a malicious node is a proposer, the normal node does not have a 2/3+ agreement, so after exposing the error log, it elects another proposer.(Error log above)

This issue has been verified, so I'm close it.
