### ISSUE TITLE
`go get` fails because `replace` directives don't work

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#198]
When I try to `go get` the panacea-core, the following error occurs. It seems [replace](https://github.com/medibloc/panacea-core/blob/388585acad2058b5de0c98ef615f8ed41eb286b6/go.mod#L38) directives don't work. This issue was also presented in the [starport](https://github.com/tendermint/starport/issues/155#issuecomment-816537618) repo.
```
go get github.com/medibloc/panacea-core/v2
go get: github.com/medibloc/panacea-core/v2@none updating to
	github.com/medibloc/panacea-core/v2@v2.0.1-a requires
	github.com/gogo/protobuf@v1.3.3: reading github.com/gogo/protobuf/go.mod at revision v1.3.3: unknown revision v1.3.3
```

But, I've seen that the cosmos-sdk is go-gettable even though it also has many replace keywords: https://github.com/cosmos/cosmos-sdk/blob/12e4be34fbd2414b10756997ca3769ebaaf6bdea/go.mod#L59.

It might be related to the #197 .

**Comment by youngjoon-lee** [comment]
The go-getting cosmos-sdk also fails with the same error:
```
go get github.com/cosmos/cosmos-sdk
go get: github.com/cosmos/cosmos-sdk@v0.40.0 updating to
	github.com/cosmos/cosmos-sdk@v0.42.7 requires
	github.com/gogo/protobuf@v1.3.3: reading github.com/gogo/protobuf/go.mod at revision v1.3.3: unknown revision v1.3.3
```

**Comment by youngjoon-lee** [comment]
Jesus... Go guys have been complaining this issue for a long time: https://github.com/golang/go/issues/30354#issuecomment-466479708

**Comment by gyuguen** [comment]
Oops, well, do we have to turn the logic back?

**Comment by youngjoon-lee** [comment]
I think we have no choice but to use `replace` directives as [cosmos-sdk](https://github.com/cosmos/cosmos-sdk/blob/adff7d804d3fbbf332c8a5967889ff9837c92f4e/go.mod#L59). Because the [gogo/protobuf](https://github.com/gogo/protobuf) isn't being maintained anymore, the Cosmos team forked it as [regen-network/protobuf](https://github.com/regen-network/protobuf). But they didn't change the [Go package name](https://github.com/regen-network/protobuf/blob/8a70ddfdaf94e68497f7b26a6896ad75e03b6616/go.mod#L1) by design. So, we have to use `replace` directives.

I'm thinking about some work-arounds.

**Comment by youngjoon-lee** [comment]
One work-around might be use `replace` directives as well in the project that requires `medibloc/panacea-core`.
```
module aaa.com/kk

go 1.16

require github.com/medibloc/panacea-core/v2 v2.0.1-a

replace google.golang.org/grpc => google.golang.org/grpc v1.33.2

replace github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.3-alpha.regen.1
```
But, they must keep in mind that the version of replaced packages must be upgraded when the panacea-core is upgraded.

**Comment by youngjoon-lee** [comment]
> One work-around might be using `replace` directives as well in the project that requires `medibloc/panacea-core`.

I found that the `cosmos/gaia` also uses this work-around, even though they don't compile proto files.
https://github.com/cosmos/gaia/blob/64ae891c9a77ea88e08d7c5056781388d6892e42/go.mod#L18
