### ISSUE TITLE
Add identity to validator

### ISSUE THREAD

**Issue by gyuguen** [medibloc/panacea-core#217]
We need to add identity to our validator.
Currently, [mintscan](https://www.mintscan.io/medibloc/validators) shows the validator's logo, but not the [big-dipper]().

### Reference
- [Cosmos guide](https://hub.cosmos.network/main/validators/validator-setup.html#edit-validator-description)
- https://keybase.io
- [IRISnet guide](https://github.com/irisnet/testnets/blob/master/fuxi/How%20to%20use%20keybase.md)

**Comment by youngjoon-lee** [comment]
@gyuguen created Keybase accounts and PGP keys.

@youngjoon-lee added those identities to each validator on the Mainnet.
https://explorer.gopanacea.org/validators

TODO: Reveal PGP signatures on corresponding websites (the website of each product).

**Comment by youngjoon-lee** [comment]
Done
