### ISSUE TITLE
Store the burn history

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#219]
Currently, coins in the burn account are silently burned and no history is stored in the Store. 

But, Ethereum shows a total burned amount as below:
![image](https://user-images.githubusercontent.com/5462944/129987964-aa81b738-2393-4021-bd88-4b5039015e0d.jpeg)

It might be also useful to store the burn history, so that the history is stored permanently. 
The incoming transactions to the burn account is not permanent. Those are cleared after hard-forks. 
Someone will definitely want to see the full burn history. 

The burn history would be defined as below:
- timestamp
- amount + denom
- burner (who sent coins to the burn account)

But, the problem is that the previous history of coins which were already burned weren't stores. For that, we may have to do hard-fork with adding a burn history manually.

**Comment by gyuguen** [comment]
It seems like a good way to store it permanently about Burn!
Well, I think It will need two storage spaces.
- Burn history storage (The above mentioned `timestamp, amount+denom, burner`)
- Total burn amount

Additionally, It would be good to provide an API that can respond to the `Total issue volume, Burn volume, Distribution volume`.
- Total issue volume: distribution + burn
- Distribution volume: total supply amount
- Burn volume: total burn amount

**Comment by youngjoon-lee** [comment]
> - Burn history storage (The above mentioned timestamp, amount+denom, burner)
> - Total burn amount

Ja. Looks good to have them.

> - Total issue volume: distribution + burn
> - Distribution volume: total supply amount
> - Burn volume: total burn amount

I didn't understand what the `distribution` means, but I think the only APIs to be implemented are:
```
$ panacead query burn total

total_burned_amounts:
- amount: "11111111"
  denom: umed
- amount: "22222222"
  denom: uyj
```
```
$ panacead query burn histories

pagination:
  next_key: ..
  total: ..
histories:
- timestamp: "2021-08-16T19:26:15.484303792Z"
  burner: "panacea1....."
  amounts:
  - amount: "11"
    denom: umed
  - amount: "22"
    denom: uyj
- timestamp: ...
  burner: ...
```
```
$ panacead query burn histories-from <burner>

pagination:
  next_key: ..
  total: ..
histories:
- timestamp: "2021-08-16T19:26:15.484303792Z"
  burner: "panacea1....."
  amounts:
  - amount: "11"
    denom: umed
  - amount: "22"
    denom: uyj
- timestamp: ...
  burner: ...
```

**Comment by youngjoon-lee** [comment]
I'm also thinking about storing only the total burned amount, without storing the full history.

It's the core limitation of Cosmos that all TXs are cleared after hard-forks.
So, other modules (staking, slashing, ...) just obey the limitation, without storing the full history to the store.
So far, I haven't seen any module that store the full history in the append-only manner.

It's true that the burn operations rarely happen. But, someone can probably make an attack by burning only 1umed multiple times in order to make our storage full.

**Comment by gyuguen** [comment]
It's not bad to save only the total burn.

I think it's good for the side we manage if there's no history left.
But if we decide to leave a history,, it seems necessary to specify the minimum burn quantity. 
(e.g. It can be burn from 1,000MED or higher.)

**Comment by youngjoon-lee** [comment]
Yeah, but it's a makeshift to put the minimal burn amount. It will finally hit the fan and make the design complicated. 
Our AOL module is the append-only model because there is no other choice. But, for the burn module, I think it's a different story. 

As similar, the staking module just store the latest view (voting power, ...) without storing the full history of delegations. The history is stored in the tx store, but it is cleared after a hard-fork. 

So, we need to think what we really wanna achieve. 
We must store the total burned amounts in order to know how many coins have been burned so far. If not, there's no way to know whether something has been burned or not before a hard-fork. 
But, I think it's not essential to store the burn history. It would be enough to keep big-dipper data for retired chains.

**Comment by gyuguen** [comment]
All right, then we can save the final amount of burn coins and check the TX of the retired chain with a history! (See account `panacea100000000000000000000000000000000nqmafp`). 

And this feature (save the final burn) would be a good idea to do so during hard-fork to save the previous history as well.(Add to `genesis.json`)
Of course, if the burn module is added before that, we can fill in the burn amount in our source, but I don't think it's a good idea.
