### ISSUE TITLE
Prepare the Cosmovisor guide for Panacea + Set it up on our infra

### ISSUE THREAD

**Issue by gyuguen** [medibloc/panacea-core#233]
### Background
* With the addition of external validator, more various aspects should be considered when upgrading software.
* Cosmos has software that automatically upgrades with just a few settings and installations.

### Goal
* Need to know what `Cosmosvisor` provides.
* Need to know how to install and use Cosmosvisor.
* Need to fill out a document that can apply Cosmosvisor to Panacea.

### Reference
[Using-cosmovisor](https://docs.cosmos.network/v0.44/migrations/chain-upgrade-guide-043.html#using-cosmovisor)
[Cosmosvisor Quick Start](https://docs.cosmos.network/v0.44/run-node/cosmovisor.html)

**Comment by gyuguen** [comment]
## Installation
```shell
go get github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor
```

## Environment
There are four variables. (two are requirement, and two are optional)

* DAEMON_HOME (Requirement)
  * This includes genesis binary and upgrade binaries.
  * `export DAEMON_HOME=$HOME/.panacea`
* DAEMON_NAME (Requirement)
  * It's the name of binary.
  * `export DAEMON_NAME=panacead`
* DAEMON_ALLOW_DOWNLOAD_BINARIES (Optional)
  * Whether to automatically download the new binary.
  * The default value is `false`.
* DAEMON_RESTART_AFTER_UPGRADE (Optional)
  * Whether to restart the process after the upgrade is completed.
  * The default value is false, so the administrator must manually restart after the upgrade.
  * `export DAEMON_RESTART_AFTER_UPGRADE=true`

## Next...
The following comments are written about manual download and execution from the beginning.

**Comment by gyuguen** [comment]
### Run the current version of mainnet with cosmovisor

Installation cosmovisor
```shell
go get github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor

export DAEMON_HOME=$HOME/.panacea

export DAEMON_NAME=panacead

export DAEMON_RESTART_AFTER_UPGRADE=true

mkdir -p $DAEMON_HOME/cosmovisor/genesis/bin

mkdir -p $DAEMON_HOME/cosmovisor/upgrades
```

Clone and check out the current `panacea-core` mainnet version. (`v2.0.1`)
```shell
git clone -b v2.0.1 https://github.com/medibloc/panacea-core.git

cd panacea-core
```

Build a binary and copy it to the genesis path of the cosmovisor.
```shell
make clean && make build

cp ./build/panacead $DAEMON_HOME/cosmovisor/genesis/bin
```

Create a new key for the validator, then add a genesis account and transaction:
```shell
cosmovisor init test --chain-id test --overwrite

cosmovisor keys add validator

cosmovisor add-genesis-account validator 1000000000umed --keyring-backend test

cosmovisor gentx validator 1000000umed --chain-id test

cosmovisor collect-gentxs

cat <<< $(jq '.app_state.gov.voting_params.voting_period = "20s" | .app_state.gov.deposit_params.min_deposit[].amount = "10000000"' $DAEMON_HOME/config/genesis.json) > $DAEMON_HOME/config/genesis.json
```

You need to run binary with cosmovisor.
```shell
# This is actually a version executed with `panacead`.
cosmovisor version
2.0.1 

cosmovisor start
```

### Upgrade
Get the binary to upgrade. 
Currently, we temporarily made `ft/233/cosmvisor` branch.
```shell
git checkout ft/233/cosmvisor
make clean && make build
```

Copy to the upgrade path of cosmvisor.
```shell
# upgrade name: test_cosmovisor
mkdir -p $DAEMON_HOME/cosmovisor/upgrades/test_cosmovisor/bin
cp ./build/panacead $DAEMON_HOME/cosmovisor/upgrades/test_cosmovisor/bin
```

Submit upgrade proposal along with a deposit and a vote.
```shell
cosmovisor tx gov submit-proposal software-upgrade test_cosmovisor --title upgrade --description upgrade --upgrade-height 50 --from validator --chain-id test --yes

cosmovisor tx gov deposit 1 10000000umed --from validator --chain-id test --yes

cosmovisor tx gov vote 1 yes --from validator --chain-id test --yes
```

The upgrade will be performed automatically at height 50.

**Comment by gyuguen** [comment]
The auto download specification has been changed from the latest master branch of Cosmovisor.

[file watcher for cosmovisor](https://github.com/cosmos/cosmos-sdk/pull/8590)

The latest cosmovisor (master branch. upcoming v1.0.0 version) is supported from 0.43.0 and above.
The 0.42.x version must use the v0.1.0 version.

Cosmovisor's guide does not fit our version because it runs on a master branch basis.

We can use `cosmovisor@0.1.0`

**Comment by gyuguen** [comment]
It's similar to manual download, but it's slightly different.

## Run the current version of mainnet with cosmovisor

Installation cosmovisor

```shell
go get github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@v0.1.0

export DAEMON_HOME=$HOME/.panacea

export DAEMON_NAME=panacead

export DAEMON_RESTART_AFTER_UPGRADE=true

export DAEMON_ALLOW_DOWNLOAD_BINARIES=true

mkdir -p $DAEMON_HOME/cosmovisor/genesis/bin
```
Clone and check out the current panacea-core mainnet version. (v2.0.1)
And build a binary and copy it to the genesis path of the cosmovisor.
```shell
git clone -b v2.0.1 https://github.com/medibloc/panacea-core.git

cd panacea-core

make clean && make build

cp ./build/panacead $DAEMON_HOME/cosmovisor/genesis/bin
```

Create a new key for the validator, then add a genesis account and transaction:
```shell
./build/panacead init test --chain-id test --overwrite

./build/panacead keys add validator

./build/panacead add-genesis-account validator 1000000000umed --keyring-backend test

./build/panacead gentx validator 1000000umed --chain-id test

./build/panacead collect-gentxs

cat <<< $(jq '.app_state.gov.voting_params.voting_period = "20s" | .app_state.gov.deposit_params.min_deposit[].amount = "10000000"' $DAEMON_HOME/config/genesis.json) > $DAEMON_HOME/config/genesis.json
```

You need to run binary with cosmovisor.
```shell
# This is actually a version executed with `panacead`.
cosmovisor version
2.0.1 

cosmovisor start
```
## Upgrade
It will skip downloading the new binary.
Submit upgrade proposal along with a deposit and a vote.

```shell
./build/panacead tx gov submit-proposal software-upgrade v2.0.2 \
--title upgrade --description upgrade --upgrade-height 20 \
--upgrade-info '{"binaries":{"linux/amd64":"https://github.com/medibloc/panacea-core/releases/download/v2.0.2/panacead-v2.0.2-linux-amd64.zip?checksum=sha256:62d0bc8ee0e3046768aa107b7386481244d55b5de0f7e11a3e96b40ed409db73","darwin/amd64":"https://github.com/medibloc/panacea-core/releases/download/v2.0.2/panacead-v2.0.2-darwin-amd64.zip?checksum=sha256:1fd86a36673f77d3734c865d5aa16073e13b477471f7dc25db544d822f38e710"}}' \
--from validator --chain-id test --yes

./build/panacead tx gov deposit 1 10000000umed --from validator --chain-id test --yes

./build/panacead tx gov vote 1 yes --from validator --chain-id test --yes
```

The upgrade will be performed automatically at height 20.
You can check the version to see if the upgrade has been successful.
```shell
cosmovisor version
2.0.2
```

**Comment by youngjoon-lee** [comment]
Awesome. This guide is a gold. Later, we can put this guide to our Gitbook.

I have a question.
From our [v2.0.2 release page](https://github.com/medibloc/panacea-core/releases/tag/v2.0.2), I saw that attachments are `.zip` type. But, in the [Gaia v5.0.5 release page](https://github.com/cosmos/gaia/releases/tag/v5.0.5), they uploaded uncompressed binaries.
Is there any reason for uploading `.zip` files?

**Comment by gyuguen** [comment]
I referred to this explanation. 
[Auto-download](https://github.com/cosmos/cosmos-sdk/tree/cosmovisor/v0.1.0/cosmovisor#auto-download)

If not compressed into `.zip`, it has a capacity of about 60MB.

And when I tested this part, the automatic upgrade proceeds normally without compressing it to `.zip`.

**Comment by youngjoon-lee** [comment]
Yes. It would make sense to upload a zip file if we should upload more than two files as the manual mentioned. For only one file, I think it's intuitive to upload a plain file as Gaia did, even though its size is about 60mb.

**Comment by youngjoon-lee** [comment]
Fortunately, https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#distributing-large-binaries :))

**Comment by gyuguen** [comment]
I got it. I'll unzip it and upload it again.

**Comment by youngjoon-lee** [comment]
I guess the downloaded binary does not work if the `/usr/lib/libwasmvm.so` doesn't exist. Let me find the way to build the static lib and embed it to panacead.

**Comment by youngjoon-lee** [comment]
I just found a hint for the static lib from https://github.com/CosmWasm/wasmd/blob/master/Dockerfile

The static lib issue is not directly relevant for existing node operators because they may already have the shared lib.

**Comment by youngjoon-lee** [comment]
Hmm. I need to take a deeper look at the static lib issue, but I'm putting what I've researched so far.

The `wasmd` uses `libwasmvm_muslc.a` only for Alpine (It's trivial that the default libc system is muslc in Alpine). But, for other Linux systems, the `wasmd` uses the shared lib: `libwasmvm.so`.

That's because the `wasmvm` provides a static lib only for Alpine.
- A static lib for alpine: https://github.com/CosmWasm/wasmvm/blob/3cf64c230a8c801ad9569abe241e00416e61dc2d/Makefile#L53
- A shared lib for linux (with glibc): https://github.com/CosmWasm/wasmvm/blob/3cf64c230a8c801ad9569abe241e00416e61dc2d/Makefile#L64
- A shared lib for macOS: https://github.com/CosmWasm/wasmvm/blob/3cf64c230a8c801ad9569abe241e00416e61dc2d/Makefile#L71

I don't know the reason why they provides a static lib only for Alpine, but it seems that there is a open-source license issue: https://github.com/CosmWasm/wasmvm/issues/45#issuecomment-576722165. I will ask about it to the `wasmvm` maintainers.

Until then, I think we have no choice but to use the shared lib. Then, the binary downloaded from our release pages on Github won't work for node operators who have never run `make build` for the `panacea-core`.

**Comment by gyuguen** [comment]
That's not good news...
Umm, Why don't you always post `libwasmvm.so` and `libwasvm.dylib` on our release tag with `panacead` binary(Or we can compress it together)?

Well, it's not a complete solution, so I feel uncomfortable.

**Comment by youngjoon-lee** [comment]
I opened a issue on the `wasmvm` github: https://github.com/CosmWasm/wasmvm/issues/259

We can upload shared libraries to our release pages, or we can recommend for users to download shared libraries from https://github.com/CosmWasm/wasmvm/tree/main/api to their `/usr/lib/` directory. But, it will cause various issues in respect of the library version management.

**Comment by youngjoon-lee** [comment]
Hm. I just downloaded a `terrad` from https://github.com/terra-money/core/releases/tag/v0.5.0. I think that binary was built with static libraries. Let me check how they did it.

**Comment by youngjoon-lee** [comment]
I just realized why the `panacead` process is not shut down even though the `panic()` is called by the `x/upgrade` module (when we don't use the cosmovisor).

A goroutine which is spawned by Tendermint calls `recover()` for the panic and stop only the state machine. 
https://github.com/tendermint/tendermint/blob/v0.34.11/consensus/state.go#L725

So, other goroutines keep running. I think this behavior is intended because the process should be able to respond on queries or provide blocks to other nodes which are not fully synced yet, so that they can reach the desired 'upgrade height'.

**Comment by youngjoon-lee** [comment]
@gyuguen 

As we discussed, we may need to put the cosmovisor guide to our Gitbook.

But, if our guide is not that different from the official cosmovisor guide: https://docs.cosmos.network/master/run-node/cosmovisor.html,
I think we can put only minimal information to our Gitbook.

For example, we can put the link of the official cosmovisor guide on the top of our document.
And then, we may need to put Panacea-specific information such as 
- Which version of the cosmovisor should be used for our latest version of `panacead`. 
- How to set environment variables (`DAEMON_*`)
- The reason why the auto-download is not supported yet

**Comment by gyuguen** [comment]
Cosmovisor has been applied to devnet and testnet.

We are planning to apply 1cosmovisor per Region on mainnet before the upgrade on October 1st.

**Comment by gyuguen** [comment]
We applied cosmovisor to some mainnet nodes and there seems to be no problem.
I will soon apply cosmovisor to other nodes on the mainnet.
