### ISSUE TITLE
NOT URGENT: Consider having a transaction for transferring NFTs (+ royalty)

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#281]
- We already know that [cw-nfts](https://github.com/CosmWasm/cw-nfts) has all contracts that we need, but we should consider whether we need a wrapper for those contracts in the `x/datapool`.

**Comment by gyuguen** [comment]
We've kicked out the wasm, and we're not using the dataPool, so we're closing this issue.
