### ISSUE TITLE
Implements Uptime feature for voting participation

### ISSUE THREAD

**Issue by gyuguen** [medibloc/panacea-core#386]
Added `Uptime` update feature according to oracle participation in voting.
The following parameters are modified.
* `uptime`: Block count for which Oracle is active. If it is not Jailed, it will be counted continuously, and if it is Jailed, it will be initialized.
* `missedVote`: If Oracle fails to vote, the count is incremented. And if the Oracle voted correctly, this value is decremented. This value is initialized when participating in voting or Jailed.
* `invalidVote`: If the oracle casts the wrong vote, the count is incremented. This value is not initialized.

Only features to increment/decrement `uptime`, `missedVote`, and `invalidVote` respectively are implemented here.

**Comment by youngjoon-lee** [comment]
I think we can close this issue since this is related to the `panacea-doracle` deprecated.
