### ISSUE TITLE
Upgrade DeactivateDeal function

### ISSUE THREAD

**Issue by inchori** [medibloc/panacea-core#492]
When buyer deactivated the deal, the remained vote need to be removed.
- Implement a `RemoveAllDataVerificationQueue` and `RemoveAllDataDeliveryQueue` in `keeper.go`

**Comment by audtlr24** [comment]
When buyer deactivated the deal, `DataVerification/Delivery` queue does not removed.

Instead, deal status become `INACTIVE_REQUESTED`, and in this state, the previously requested `sellData` will be voted. When the deal status is `INACTIVE_REQUESTED`, additional `sellData` requests will be rejected.

After all previously requested `sellData` have been voted, deal status become `INACTIVE` and buyer can get a refund remaining coins in the deal account.

So, let's implement the following.
- change `DeactivateDeal` keeper function
- implement check function that all previously requested `sellData` have been voted or not
- implement refund function when all previously requested `sellData` have been voted
- applying above functions

**Comment by audtlr24** [comment]
There are some changes like below:
- deal status `INACTIVE_REQUESTED` renamed `DEACTIVATING`
- deal status `INACTIVE` renamed `DEACTIVATED`
- when the deal_status is `DEACTIVATING`, panacea calculate `deactivate_height` by `cur_height + k * voting_period` (the `k` is set by params)
-  when the block reach `deactivate_height`, deal status become `DEACTIVATED` and all the remaining coins in deal account refund to buyer

**Comment by youngjoon-lee** [comment]
I think we can close this issue because this is related with the `panacea-doracle` (deprecated).
