### ISSUE TITLE
Cannot send transaction using keplr

### ISSUE THREAD

**Issue by thisisommore** [medibloc/panacea-core#495]
When I try to send 10 med I get this error
```
Fail to send token: insufficient fees; got: 4756umed required: 475520umed: insufficient fee
```
<img width="276" alt="image" src="https://user-images.githubusercontent.com/51229945/200191661-8218d438-2c67-4358-af7c-3637d9dd1ff2.png">

My address - `panacea1q03mcltqqk7cllqvslt294kkl76tvqnkrtwhlu`
Same error with high and low gas settings.
Please help me in this

**Comment by gyuguen** [comment]
Hi @thisisommore .
Did you use the chrome plugin?

**Comment by thisisommore** [comment]
Yes, chrome extension on brave browser.

**Comment by gyuguen** [comment]
I think you need to delete MediBloc in Beta support.
And you need to re-register MediBloc chain at https://app.osmosis.zone.
This is probably because keplr keep old medibloc information.

![image](https://user-images.githubusercontent.com/10514738/200226084-0b4f6d3e-5176-4607-b234-fd20ddfe4c68.png)

**Comment by thisisommore** [comment]
Thanks for the information, this should work, I currently switched the
wallet.
Feel free to close this now, thanks again.
