### ISSUE TITLE
Consider using `chain-id` as a DID network-id

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#52]
Currently, [clients](https://github.com/medibloc/panacea-js/blob/1b6284f9e21e8ffdab6d0c1e7300d84a92198401/example/did.js#L37) should specify a [network-id](https://github.com/medibloc/panacea-core/blob/master/docs/did.md#did-method-specific-identifier) when creating a DID (e.g. `mainnet` or `testnet`).
Also, the `panacea-core` [doesn't check](https://github.com/medibloc/panacea-core/blob/25c4cdb326b97cb317495f7e7db36daf10b21aec/x/did/types/did.go#L36) if it's correct, or not.

To make `panacea-core` check it, we need to add one more parameter (`network-id`) for `panacea-core`.

Instead, I'd like to consider using the [chain-id](https://medibloc.gitbook.io/panacea-core/guide/how-to-deploy-own-panacea-testnet#create-genesis-file-and-start-the-network) as a network-id for DID.

What do you think about it? @cl9200 

Then, clients can get the chain-id from `panacea-core` when creating DIDs. Also, the `panacea-core` can validate DIDs using its chain-id. No additional parameter is needed.

**Comment by youngjoon-lee** [comment]
Hmm. It seems it's not reasonable because the chain-id has the max length 50 bytes: https://docs.tendermint.com/master/spec/consensus/signing.html#chainid

**Comment by youngjoon-lee** [comment]
Another option would be not having the network-id as Sovrin does.
```
BEFORE: did:panacea:mainnet:fjoiqjeroijpqwer
AFTER:  did:panacea:fjoiqjeroijpqwer
```
But, I'm not sure.

**Comment by cl9200** [comment]
> Currently, [clients](https://github.com/medibloc/panacea-js/blob/1b6284f9e21e8ffdab6d0c1e7300d84a92198401/example/did.js#L37) should specify a [network-id](https://github.com/medibloc/panacea-core/blob/master/docs/did.md#did-method-specific-identifier) when creating a DID (e.g. `mainnet` or `testnet`).
> Also, the `panacea-core` [doesn't check](https://github.com/medibloc/panacea-core/blob/25c4cdb326b97cb317495f7e7db36daf10b21aec/x/did/types/did.go#L36) if it's correct, or not.
> 
> To make `panacea-core` check it, we need to add one more parameter (`network-id`) for `panacea-core`.
> 
> Instead, I'd like to consider using the [chain-id](https://medibloc.gitbook.io/panacea-core/guide/how-to-deploy-own-panacea-testnet#create-genesis-file-and-start-the-network) as a network-id for DID.
> 
> What do you think about it? @cl9200
> 
> Then, clients can get the chain-id from `panacea-core` when creating DIDs. Also, the `panacea-core` can validate DIDs using its chain-id. No additional parameter is needed.

The chain-id can be changed with each upgrade, so I think there may be a problem with using chain-id as the network-id.
For example, when cosmos is upgraded, the chain-id is changed from cosmoshub-1 to cosmoshub-2.

**Comment by youngjoon-lee** [comment]
Yeah. Makes sense. Then, let's keep `mainnet` and `testnet`.
We can probably add a parameter `network-id` in the `config.json`, so panacea-core can validate DIDs

**Comment by youngjoon-lee** [comment]
Resolved by https://github.com/medibloc/panacea-core/pull/57.
(Removing the network ID, instead of using chain-id).
