### ISSUE TITLE
Add a `Consent` proto type

### ISSUE THREAD

**Issue by inchori** [medibloc/panacea-core#588]
When the providers submit consent, the provider will use `Consent` proto type. So, add a `Consent` proto type and put the `Certificate` field like following code: 
```proto
message Consent {
     Certificate certificate = 1;
}
```

**Comment by H4NLee** [comment]
I expected that providers use `MsgSubmitConsent` to submit their consents. Could you elaborate the need for `Consent` proto type?

```proto
message MsgSubmitConsent {
  Certificate certificate = 1;
}
```

**Comment by inchori** [comment]
I remembered that we discussed about adding a `consent` type. So does you mean that not adding a `consent` proto type,  but adding a just `consent` data type?

**Comment by H4NLee** [comment]
Ah! I remembered now. I see. Thanks!
