### ISSUE TITLE
Enhance the AOL msg validation

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-core#65]
There might be some missing validations, such as regex checks.

**Comment by youngjoon-lee** [comment]
@cl9200 
It seems that I should check if string values aren't empty as mentioned in this [TODO](https://github.com/medibloc/panacea-core/blob/5a8f061c4b0e4266fdee6f2da367497cc12d2461/x/aol/types/msgs.go#L108), but I'm careful to define the acceptable character set for topic, description, key and value.

For descriptions, keys and values, any binary stuff should be acceptable.
For topics, how about accepting only `a-z`, `A-Z`, `0-9`, `.`, `_` and `-`, as [Kafka does for its topics](https://www.ibm.com/support/knowledgecenter/SSMKHH_10.0.0/com.ibm.etools.mft.doc/bz91041_.html).

What do you think about it?

**Comment by cl9200** [comment]
I think that would be good!
