### ISSUE TITLE
panacea-core v2 installation error

### ISSUE THREAD

**Issue by olimdzhon** [medibloc/panacea-core#668]
Gm, i'm trying to install panacea-core for validator running from this docs https://docs.gopanacea.org/for-validators/1-cli-installation. And it gives me the following error:

root@hostname:~/panacea-core# go get github.com/medibloc/panacea-core/v2
go: downloading github.com/medibloc/panacea-core v1.3.3
go: module github.com/medibloc/panacea-core@upgrade found (v1.3.3), but does not contain package github.com/medibloc/panacea-core/v2

How can i install github.com/medibloc/panacea-core/v2?

**Comment by gyuguen** [comment]
Sorry for the late response.
I think it would be good to add the version as shown below.
```
go get github.com/medibloc/panacea-core/v2@latest
```

**Comment by olimdzhon** [comment]
> Sorry for the late response. I think it would be good to add the version as shown below.
> 
> ```
> go get github.com/medibloc/panacea-core/v2@latest
> ```

hey mate, I launched the validator without this Go installation, please tell me if this somehow affects the operation of the validator? Or is it works without this installation?

**Comment by gyuguen** [comment]
> > Sorry for the late response. I think it would be good to add the version as shown below.
> 
> > 
> 
> > ```
> 
> > go get github.com/medibloc/panacea-core/v2@latest
> 
> > ```
> 
> 
> 
> hey mate, I launched the validator without this Go installation, please tell me if this somehow affects the operation of the validator? Or is it works without this installation?

Absolutely, our validator can operate without that specific command. 
I framed my response with the anticipation that our module would be utilized within other applications, ensuring versatility and seamless integration.

**Comment by olimdzhon** [comment]
> > > Sorry for the late response. I think it would be good to add the version as shown below.
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > go get github.com/medibloc/panacea-core/v2@latest
> > 
> > 
> > > 
> > 
> > 
> > hey mate, I launched the validator without this Go installation, please tell me if this somehow affects the operation of the validator? Or is it works without this installation?
> 
> Absolutely, our validator can operate without that specific command. I framed my response with the anticipation that our module would be utilized within other applications, ensuring versatility and seamless integration.

thank you, sir
